export const MS_ANSWERS = Object.freeze(Object.fromEntries(`
How can Malaysian businesses get more online exposure?|Bagaimanakah perniagaan Malaysia boleh meningkatkan pendedahan dalam talian?
Make it easy for people to find your business, understand what you offer and reach your website or social profile. Rankoff adds a public business listing and a sponsored position to that journey. The live board shows the current entry price and currency.|Mudahkan orang mencari perniagaan anda, memahami tawaran anda dan melawat laman web atau profil sosial anda. Rankoff menyediakan penyenaraian perniagaan awam dan kedudukan tajaan. Papan langsung menunjukkan harga permulaan dan mata wang semasa.
What does a Rankoff listing include?|Apakah yang disertakan dalam penyenaraian Rankoff?
A place on the public board and in your selected industry. Visitors can browse businesses by industry, open a listing and follow its website or social-profile link.|Tempat pada papan awam dan dalam industri pilihan anda. Pelawat boleh melayari perniagaan mengikut industri, membuka penyenaraian dan mengikuti pautan laman web atau profil sosialnya.
A shareable business page. It brings together your business name, description, destination link, current sponsored position, total paid and tracked clicks. Where sourced details are available, it also shows services and location.|Halaman perniagaan yang boleh dikongsi. Ia menghimpunkan nama, penerangan, pautan destinasi, kedudukan tajaan semasa, jumlah dibayar dan klik direkodkan. Butiran perkhidmatan dan lokasi turut dipaparkan apabila sumbernya tersedia.
A ranking card to share. Use the share control on your listing to create a card showing your position at that time, then share it with your own audience.|Kad kedudukan untuk dikongsi. Gunakan fungsi kongsi pada penyenaraian anda untuk menghasilkan kad yang menunjukkan kedudukan pada waktu itu, kemudian kongsikannya dengan khalayak anda.
Help customers understand your business|Bantu pelanggan memahami perniagaan anda
Keep your public website or profile current: use a recognisable business name, describe your actual services, state your location or service area, and provide a working contact or booking route. Include opening hours when they are confirmed.|Pastikan laman web atau profil awam anda terkini: gunakan nama perniagaan yang mudah dikenali, terangkan perkhidmatan sebenar, nyatakan lokasi atau kawasan perkhidmatan dan sediakan cara menghubungi atau membuat tempahan. Sertakan waktu operasi yang telah disahkan.
For examples, explore Hypex Auto’s automotive services in Wangsa Maju and Express Queen Lash’s eyelash services at The Strand KD. Their Rankoff pages link to the businesses’ own public sources.|Sebagai contoh, lihat perkhidmatan automotif Hypex Auto di Wangsa Maju dan perkhidmatan bulu mata Express Queen Lash di The Strand KD. Halaman Rankoff mereka memautkan sumber awam perniagaan sendiri.
How much does it cost, and how long does the listing stay?|Berapakah kosnya, dan berapa lama penyenaraian kekal?
The live board shows the current minimum and currency. Payments for the same destination accumulate, and the highest settled total ranks first in the selected industry and timeframe. The current price to claim a position appears before checkout. Being overtaken changes your position; it does not remove your listing.|Papan langsung menunjukkan minimum dan mata wang semasa. Bayaran untuk destinasi yang sama dikumpulkan, dan jumlah selesai tertinggi menduduki tempat pertama bagi industri dan tempoh pilihan. Harga semasa untuk mendapatkan kedudukan dipaparkan sebelum pembayaran. Dipintas mengubah kedudukan anda; ia tidak membuang penyenaraian.
How does this fit alongside social media and advertising?|Bagaimanakah ini melengkapi media sosial dan pengiklanan?
Use your website or social profile for detailed information and enquiries, social posts to reach your followers, and ads when you want paid distribution. Your Rankoff page provides another public place to discover and share the business. The sponsored position is determined by payment, rather than a service-quality score.|Gunakan laman web atau profil sosial untuk maklumat terperinci dan pertanyaan, siaran sosial untuk pengikut, serta iklan untuk pengedaran berbayar. Halaman Rankoff menjadi satu lagi tempat awam untuk menemui dan berkongsi perniagaan. Kedudukan tajaan ditentukan oleh bayaran, bukan skor kualiti perkhidmatan.
Where can I see the response?|Di manakah saya boleh melihat respons?
Open your listing to see its tracked clicks and ranking record. These clicks count redirects from Rankoff to your linked website or profile; repeat and automated traffic may be included. Use your own website or booking records to follow what visitors do after they arrive.|Buka penyenaraian untuk melihat klik direkodkan dan rekod kedudukan. Klik ini mengira pengalihan dari Rankoff ke laman web atau profil anda; trafik berulang dan automatik mungkin disertakan. Gunakan rekod laman web atau tempahan sendiri untuk memahami tindakan pelawat selepas tiba.
Business Exposure in Malaysia · 商家曝光 · RANKOFF|Pendedahan Perniagaan di Malaysia | RANKOFF
Explore Rankoff business listings: a public sponsored position, a shareable business page and tracked clicks. 了解 Rankoff 商家展示：公开赞助位置、商家资料页与追踪点击。|Terokai penyenaraian Rankoff: kedudukan tajaan awam, halaman perniagaan yang boleh dikongsi dan klik direkodkan.
What is a pay-to-rank leaderboard?|Apakah papan kedudukan berbayar?
How does Rankoff ranking work?|Bagaimanakah kedudukan Rankoff ditentukan?
How can I sponsor a website or social profile?|Bagaimanakah saya menaja laman web atau profil sosial?
FAQ / 常见问题|Soalan lazim
See the live board →|Lihat papan langsung →
More answers|Panduan lain
see the board for the current listings, total paid and tracked clicks|lihat papan untuk penyenaraian semasa, jumlah dibayar dan klik direkodkan
A pay-to-rank leaderboard is a public advertising board where placement is determined by totals paid. Each website or social profile has a recorded sponsored total. Links with higher totals paid appear in higher positions.|Papan kedudukan berbayar ialah papan iklan awam yang menentukan penempatan berdasarkan jumlah bayaran. Setiap laman web atau profil sosial mempunyai jumlah tajaan yang direkodkan. Pautan dengan jumlah bayaran lebih tinggi muncul pada kedudukan lebih tinggi.
The payment purchases an advertising placement at a published price. It does not represent an editorial recommendation, customer rating or assessment of business quality. Visitors can see that the placement is sponsored and can compare the recorded amounts directly.|Bayaran membeli penempatan iklan pada harga yang diumumkan. Ia bukan cadangan editorial, penilaian pelanggan atau penilaian kualiti perniagaan. Pelawat boleh melihat bahawa penempatan itu ditaja dan membandingkan jumlah yang direkodkan secara langsung.
Payments accumulate on the public link rather than the person making the payment. A business owner, customer, supporter or marketing agency may sponsor the same link. Each settled payment increases that link’s total. The payer does not receive ownership or editing rights over the website or social profile.|Pembayaran terkumpul pada pautan awam, bukan pada individu yang membayar. Pemilik perniagaan, pelanggan, penyokong atau agensi pemasaran boleh menaja pautan yang sama. Setiap pembayaran yang selesai menambah jumlah pautan itu. Pembayar tidak mendapat hak milik atau hak menyunting laman web atau profil sosial tersebut.
Rankoff is a public sponsored leaderboard for businesses, products and services across countries. An eligible public website or social profile can receive a listing. Browse software, design, marketing and other industries, alongside local shops and services. The live board shows the current entry price, currency and price to claim a position.|Rankoff ialah papan kedudukan tajaan awam untuk perniagaan, produk dan perkhidmatan merentas negara. Laman web atau profil sosial awam yang layak boleh disenaraikan. Terokai perisian, reka bentuk, pemasaran dan industri lain, bersama kedai serta perkhidmatan tempatan. Papan langsung menunjukkan harga permulaan, mata wang dan harga mendapatkan kedudukan semasa.
Every live listing receives a permanent Rankoff page showing its current position, sponsored total paid and tracked click count. The board is public and current:|Setiap penyenaraian aktif mendapat halaman Rankoff kekal yang menunjukkan kedudukan semasa, jumlah tajaan dibayar dan bilangan klik direkodkan. Papan ini terbuka dan terkini:
What determines a listing’s position?|Apakah yang menentukan kedudukan penyenaraian?
Position is determined by the sponsored total paid recorded for the public link.|Kedudukan ditentukan oleh jumlah tajaan dibayar yang direkodkan untuk pautan awam itu.
Is the position a quality rating?|Adakah kedudukan itu penilaian kualiti?
No. It is a disclosed advertising placement, not an editorial review or quality assessment.|Tidak. Ia ialah penempatan iklan yang dinyatakan secara terbuka, bukan ulasan editorial atau penilaian kualiti.
Who can sponsor a link?|Siapakah yang boleh menaja pautan?
Anyone may sponsor an eligible public website or social profile. Payments accumulate on the link.|Sesiapa sahaja boleh menaja laman web atau profil sosial awam yang layak. Pembayaran terkumpul pada pautan itu.
What information is public?|Apakah maklumat yang dipaparkan kepada umum?
The listing page shows its position, total paid, tracked clicks and destination link.|Halaman penyenaraian menunjukkan kedudukan, jumlah dibayar, klik direkodkan dan pautan destinasi.
Does each industry have a separate board?|Adakah setiap industri mempunyai papan berasingan?
Yes. Rankoff has 19 industries, each with its own ordering and published price for the first position.|Ya. Setiap industri Rankoff mempunyai susunan sendiri dan harga tempat pertama yang diumumkan.
Rankoff orders public websites and social profiles by their sponsored totals paid. A higher total paid places a link higher on its selected industry board. The amount beside each listing is the advertising value already recorded for that link.|Rankoff menyusun laman web dan profil sosial awam mengikut jumlah tajaan dibayar. Jumlah lebih tinggi menempatkan pautan lebih tinggi pada papan industri yang dipilih. Jumlah di sebelah penyenaraian ialah nilai iklan yang telah direkodkan untuk pautan itu.
A new payment does not create ownership of the listing. It adds advertising value to the normalized public link. If several people sponsor the same eligible link, their settled payments are added to one total. This allows a business, customer, supporter or agency to contribute to the same public placement.|Pembayaran baharu tidak memberikan pemilikan penyenaraian. Ia menambah nilai iklan pada pautan awam yang diseragamkan. Jika beberapa orang menaja pautan layak yang sama, pembayaran mereka yang selesai dijumlahkan. Ini membolehkan perniagaan, pelanggan, penyokong atau agensi menyumbang kepada penempatan awam yang sama.
Rankoff contains 19 industries. A listing must be placed in the industry that describes its business or activity. A hardware retailer may use Retail & Ecommerce, while a pickleball facility may use Sports & Fitness. The type of link does not determine the market: an Instagram profile can represent a retailer, clinic, property agent or creator.|Rankoff merangkumi pelbagai industri. Penyenaraian mesti diletakkan dalam industri yang menggambarkan perniagaan atau aktivitinya. Peruncit perkakasan boleh memilih Runcit & E-dagang, manakala kemudahan pickleball boleh memilih Sukan & Kecergasan. Jenis pautan tidak menentukan industri: profil Instagram boleh mewakili peruncit, klinik, ejen hartanah atau pencipta.
Each industry has its own board and its own published price for the first position. A placement in one industry does not automatically determine its position in another industry.|Setiap industri mempunyai papan dan harga tempat pertama sendiri. Kedudukan dalam satu industri tidak secara automatik menentukan kedudukan dalam industri lain.
Every live listing has a permanent public page recording its current position, total paid and tracked click count. Clicks provide reporting information but do not set the placement order.|Setiap penyenaraian aktif mempunyai halaman awam kekal yang merekodkan kedudukan semasa, jumlah dibayar dan bilangan klik direkodkan. Klik memberikan maklumat pelaporan tetapi tidak menentukan susunan kedudukan.
What happens when the same link receives another payment?|Apakah yang berlaku apabila pautan sama menerima bayaran lagi?
The new settled payment is added to that link’s existing sponsored total.|Pembayaran baharu yang selesai ditambah kepada jumlah tajaan sedia ada pautan itu.
Does the payer own the listing?|Adakah pembayar memiliki penyenaraian?
No. Payment purchases advertising placement and does not provide ownership or editing rights.|Tidak. Bayaran membeli penempatan iklan dan tidak memberikan hak milik atau hak menyunting.
Do clicks affect the position?|Adakah klik mempengaruhi kedudukan?
No. Tracked clicks are reporting data. The placement order is based on sponsored totals paid. Repeat clicks count and automated traffic is not filtered, so a click is not a unique visitor, enquiry or sale.|Tidak. Klik direkodkan ialah data pelaporan. Susunan kedudukan berdasarkan jumlah tajaan dibayar. Klik berulang dikira dan trafik automatik tidak ditapis, jadi satu klik bukan seorang pelawat unik, pertanyaan atau jualan.
Does the social platform determine the industry?|Adakah platform sosial menentukan industri?
No. The industry describes the business or activity, not the platform carrying the link.|Tidak. Industri menggambarkan perniagaan atau aktiviti, bukan platform yang menempatkan pautan.
What appears on the permanent page?|Apakah yang dipaparkan pada halaman kekal?
It displays the public link, current position, total paid and tracked click count.|Ia memaparkan pautan awam, kedudukan semasa, jumlah dibayar dan bilangan klik direkodkan.
Rankoff allows anyone to purchase advertising placement for an eligible public website or social profile. The process starts with the public destination link, not the identity of the payer.|Rankoff membolehkan sesiapa sahaja membeli penempatan iklan untuk laman web atau profil sosial awam yang layak. Proses bermula dengan pautan destinasi awam, bukan identiti pembayar.
Enter a public link.|Masukkan pautan awam.
Submit the website or public social-profile address that should appear on Rankoff.|Hantar alamat laman web atau profil sosial awam yang patut dipaparkan pada Rankoff.
Select its industry.|Pilih industrinya.
Choose the industry that describes the business or activity; the platform carrying the link does not determine its industry.|Pilih industri yang menggambarkan perniagaan atau aktiviti; platform yang menempatkan pautan tidak menentukan kategorinya.
Review the placement.|Semak penempatan.
Rankoff shows the published advertising price and the position associated with the payment.|Rankoff menunjukkan harga iklan yang diumumkan dan kedudukan yang berkaitan dengan bayaran.
Complete payment.|Selesaikan pembayaran.
The live board and payment review show the current minimum and currency. Only settled amounts are included in the listing total.|Papan langsung dan semakan pembayaran menunjukkan minimum serta mata wang semasa. Hanya jumlah yang telah diselesaikan dimasukkan dalam jumlah penyenaraian.
Software, design, marketing and other providers can use a listing to explain services they deliver across borders. Local shops and services can help nearby visitors understand their offering. Check the business's own sources for its location and service area; a country label does not mean it serves every customer in that country.|Penyedia perisian, reka bentuk, pemasaran dan perkhidmatan lain boleh menggunakan penyenaraian untuk menerangkan perkhidmatan merentas sempadan. Kedai dan perkhidmatan tempatan boleh membantu pelawat berdekatan memahami tawaran mereka. Semak sumber perniagaan sendiri untuk lokasi dan kawasan perkhidmatan; label negara tidak bermaksud ia melayani setiap pelanggan di negara itu.
A public listing gives visitors a route to the linked business. Sponsored positions reflect payments and do not assess service quality or guarantee traffic, customers, search rankings or AI citations.|Penyenaraian awam menyediakan laluan untuk pelawat ke perniagaan yang dipautkan. Kedudukan tajaan mencerminkan bayaran dan tidak menilai kualiti perkhidmatan atau menjamin trafik, pelanggan, kedudukan carian atau rujukan AI.
View the public record.|Lihat rekod awam.
The listing receives a permanent page showing its position, total paid and tracked clicks.|Penyenaraian mendapat halaman kekal yang menunjukkan kedudukan, jumlah dibayar dan klik direkodkan.
Payments accumulate on the normalized link. If a website or social profile is already listed, another settled payment increases the same listing’s sponsored total. It does not create a second record for the same normalized destination.|Pembayaran terkumpul pada pautan yang diseragamkan. Jika laman web atau profil sosial sudah disenaraikan, pembayaran lain yang selesai menambah jumlah tajaan penyenaraian yang sama. Ia tidak mencipta rekod kedua untuk destinasi sama.
The payer may be the business owner, a customer, a supporter or an agency. Payment does not provide access to the destination account and does not permit the payer to edit its profile information. Rankoff presents the placement as sponsored advertising.|Pembayar boleh terdiri daripada pemilik perniagaan, pelanggan, penyokong atau agensi. Bayaran tidak memberikan akses kepada akaun destinasi atau membenarkan pembayar menyunting maklumat profilnya. Rankoff memaparkan penempatan itu sebagai iklan tajaan.
Rankoff is new, and the figures on the board are the real ones:|Rankoff masih baharu, dan angka pada papan ialah rekod sebenar:
Must I own the website or social profile?|Adakah saya perlu memiliki laman web atau profil sosial itu?
No. Anyone may sponsor an eligible public link. Payment does not provide ownership or editing rights.|Tidak. Sesiapa sahaja boleh menaja pautan awam yang layak. Bayaran tidak memberikan hak milik atau hak menyunting.
What is the starting amount?|Berapakah jumlah permulaan?
The live board shows the current minimum and currency. The applicable published price is shown before payment.|Papan langsung menunjukkan minimum dan mata wang semasa. Harga yang berkenaan dipaparkan sebelum pembayaran.
Can I sponsor an existing listing?|Bolehkah saya menaja penyenaraian sedia ada?
Yes. A settled payment increases the sponsored total attached to that normalized link.|Ya. Pembayaran yang selesai menambah jumlah tajaan pautan yang diseragamkan itu.
How should I choose an industry?|Bagaimanakah saya memilih industri?
Choose the industry that describes the business or activity, regardless of the platform carrying the destination.|Pilih industri yang menggambarkan perniagaan atau aktiviti, tanpa mengira platform destinasi.
What happens after settlement?|Apakah yang berlaku selepas pembayaran selesai?
The public board updates and the listing page records its position, total paid and tracked clicks.|Papan awam dikemas kini dan halaman penyenaraian merekodkan kedudukan, jumlah dibayar dan klik direkodkan.
`.trim().split('\n').map(line => {const i=line.indexOf('|');return [line.slice(0,i),line.slice(i+1)];})));
