// Translation of the existing English policies; English remains authoritative.
export const MS_LEGAL = Object.freeze(Object.fromEntries(`
Advertising measurement|Pengukuran pengiklanan
We use Meta Pixel to measure page visits and advertising performance. Meta may receive page URLs, browser and device information, and cookie identifiers. See Meta’s Privacy Policy for how Meta uses this information.|Kami menggunakan Meta Pixel untuk mengukur lawatan halaman dan prestasi pengiklanan. Meta mungkin menerima URL halaman, maklumat pelayar dan peranti serta pengecam kuki. Rujuk Dasar Privasi Meta untuk cara Meta menggunakan maklumat ini.
Meta Privacy Policy|Dasar Privasi Meta
Trust center|Pusat kepercayaan
Clear rules for a paid public rank.|Peraturan jelas untuk kedudukan awam berbayar.
These policies explain how RANKOFF listings, rankings, data, and payments work. Checkout is processed through a secure Dodo Payments session.|Dasar ini menerangkan cara penyenaraian, kedudukan, data dan pembayaran RANKOFF berfungsi. Pembayaran diproses melalui sesi Dodo Payments yang selamat.
Legal pages|Halaman undang-undang
Last updated September 8, 2026|Kemas kini terakhir 8 September 2026
RANKOFF is a public sponsored leaderboard. A listing's cumulative payment total determines its sponsored position. It is not an editorial review, endorsement, or organic search ranking.|RANKOFF ialah papan kedudukan tajaan awam. Jumlah bayaran terkumpul sesuatu penyenaraian menentukan kedudukan tajaannya. Ia bukan ulasan editorial, sokongan atau kedudukan carian organik.
Advertising, not a contest|Pengiklanan, bukan pertandingan
RANKOFF is a paid advertising placement service. Rank is determined solely by cumulative settled payments — nothing else. There are no prizes, rewards, draws, raffles, gifts, or winnings of any kind, and no element of chance anywhere in the service. A payment purchases advertising placement only; it is not a wager, a deposit, an investment, or an entry into any competition, lottery, or game.|RANKOFF ialah perkhidmatan penempatan iklan berbayar. Kedudukan ditentukan semata-mata oleh jumlah pembayaran terkumpul yang telah diselesaikan. Tiada hadiah, ganjaran, cabutan, pemberian atau kemenangan dalam apa-apa bentuk, dan tiada unsur nasib dalam perkhidmatan ini. Bayaran hanya membeli penempatan iklan; ia bukan pertaruhan, deposit, pelaburan atau penyertaan dalam pertandingan, loteri atau permainan.
New listings start at the minimum shown on the board and use whole units of the board's displayed currency (Malaysian Ringgit).|Penyenaraian baharu bermula pada minimum yang dipaparkan pada papan dan menggunakan unit penuh mata wang yang dipaparkan (Ringgit Malaysia).
Payments for the same listing add together: a listing's rank reflects the total of all its settled payments.|Pembayaran untuk penyenaraian yang sama dijumlahkan: kedudukannya mencerminkan jumlah semua pembayaran yang telah diselesaikan.
A higher cumulative total ranks above a lower total. The minimum shown in the payment form applies to each new payment, not to the gap between two listings.|Jumlah terkumpul yang lebih tinggi berada di atas jumlah yang lebih rendah. Minimum dalam borang pembayaran terpakai kepada setiap pembayaran baharu, bukan jurang antara dua penyenaraian.
Equal totals keep their placement order; the listing that reached that total first ranks higher.|Jumlah yang sama mengekalkan susunan penempatan; penyenaraian yang mencapai jumlah itu terlebih dahulu berada lebih tinggi.
Today ranks activity in a rolling 24-hour window. The same settled payment contributes to all-time totals.|Paparan hari ini menyusun aktiviti dalam tempoh 24 jam bergerak. Pembayaran yang sama turut menyumbang kepada jumlah sepanjang masa.
Each confirmed challenge is a separate one-time charge for the full amount shown at checkout.|Setiap tuntutan kedudukan yang disahkan ialah caj sekali bayar yang berasingan untuk jumlah penuh yang ditunjukkan semasa pembayaran.
What may be listed|Perkara yang boleh disenaraikan
An eligible public product website or public social profile may be sponsored by its owner, an authorized representative, a customer, a supporter, or an agency. Sponsoring a link does not grant ownership or editing rights and must not be presented as authorization, endorsement, or affiliation. No adult content, invite or group-chat links, malware, scams, impersonation, unlawful offers, counterfeit goods, or links that hide the destination.|Laman web produk awam atau profil sosial awam yang layak boleh ditaja oleh pemilik, wakil yang diberi kuasa, pelanggan, penyokong atau agensi. Menaja pautan tidak memberikan hak milik atau hak menyunting dan tidak boleh digambarkan sebagai kebenaran, sokongan atau hubungan rasmi. Kandungan dewasa, pautan jemputan atau sembang kumpulan, perisian hasad, penipuan, penyamaran, tawaran menyalahi undang-undang, barangan tiruan atau pautan yang menyembunyikan destinasi tidak dibenarkan.
Listings are public. The listed party may request removal. We may refuse, recategorize, hide, or remove a listing that breaks these rules or creates legal, safety, or reputational risk.|Penyenaraian bersifat awam. Pihak yang disenaraikan boleh meminta penyingkiran. Kami boleh menolak, menukar kategori, menyembunyikan atau membuang penyenaraian yang melanggar peraturan ini atau menimbulkan risiko undang-undang, keselamatan atau reputasi.
Service agreement|Perjanjian perkhidmatan
By browsing RANKOFF, submitting a listing, or completing production checkout, you agree to these Terms and the Privacy Policy. You must be at least 18 and able to enter a binding contract.|Dengan melayari RANKOFF, menghantar penyenaraian atau menyelesaikan pembayaran sebenar, anda bersetuju dengan Terma ini dan Dasar Privasi. Anda mestilah berumur sekurang-kurangnya 18 tahun dan berkeupayaan membuat kontrak yang mengikat.
What a payment means|Maksud pembayaran
A payment buys the sponsored placement that its settled amount supports, determined solely and deterministically by comparing totals paid. It does not promise clicks, traffic, customers, revenue, a fixed rank, or a specific duration. Another buyer may pay more and move the listing down.|Bayaran membeli penempatan tajaan yang disokong oleh jumlah pembayaran yang telah diselesaikan, ditentukan hanya melalui perbandingan jumlah dibayar. Ia tidak menjanjikan klik, trafik, pelanggan, hasil, kedudukan tetap atau tempoh tertentu. Pembeli lain mungkin membayar lebih dan menyebabkan penyenaraian turun kedudukan.
Paid-placement disclosure|Pendedahan penempatan berbayar
Every position on the board is paid advertising and is labelled as sponsored, in line with applicable advertising-disclosure requirements, including the Malaysian Communications and Multimedia Content Code. You may describe your listing as a sponsored placement or advertisement. You may not present a RANKOFF rank as an editorial award, a merit-based ranking, a certification, or evidence of product quality.|Setiap kedudukan pada papan ialah iklan berbayar dan dilabelkan sebagai tajaan, selaras dengan keperluan pendedahan pengiklanan yang berkenaan, termasuk Kod Kandungan Komunikasi dan Multimedia Malaysia. Anda boleh menyifatkan penyenaraian anda sebagai penempatan tajaan atau iklan. Anda tidak boleh menggambarkan kedudukan RANKOFF sebagai anugerah editorial, kedudukan berasaskan merit, pensijilan atau bukti kualiti produk.
Your responsibilities|Tanggungjawab anda
You confirm that the submitted destination is an eligible public page and that you will not falsely claim ownership, authorization, endorsement, or affiliation. If you provide any listing information, it must be accurate. The destination and placement must follow applicable advertising, privacy, intellectual-property, consumer, and regulated-industry laws. You may not manipulate clicks, bypass limits, scrape the board for a competing service, or submit a deceptive destination.|Anda mengesahkan bahawa destinasi yang dihantar ialah halaman awam yang layak dan anda tidak akan membuat dakwaan palsu tentang pemilikan, kebenaran, sokongan atau hubungan rasmi. Maklumat penyenaraian yang anda berikan mestilah tepat. Destinasi dan penempatan mesti mematuhi undang-undang pengiklanan, privasi, harta intelek, pengguna dan industri terkawal yang berkenaan. Anda tidak boleh memanipulasi klik, memintas had, mengambil data papan untuk perkhidmatan pesaing atau menghantar destinasi yang mengelirukan.
Refunds and availability|Bayaran balik dan ketersediaan
Production ranking payments are intended to be final because placement begins when payment settles. Being outranked, receiving fewer clicks than expected, or later removal for a rules breach does not create a refund, except where mandatory law requires otherwise. The service is provided as-is and may change, pause, or become unavailable.|Pembayaran kedudukan sebenar dimaksudkan sebagai muktamad kerana penempatan bermula apabila pembayaran selesai. Dipintas, menerima kurang klik daripada jangkaan atau dibuang kemudian kerana melanggar peraturan tidak memberikan hak bayaran balik, kecuali jika diwajibkan undang-undang. Perkhidmatan disediakan seadanya dan mungkin berubah, dihentikan sementara atau tidak tersedia.
RANKOFF is not responsible for third-party destination sites or provider outages.|RANKOFF tidak bertanggungjawab terhadap laman destinasi pihak ketiga atau gangguan penyedia.
Data practices|Amalan data
RANKOFF is designed to collect only the information needed to operate the board, prevent abuse, support checkout, and understand aggregate usage.|RANKOFF direka untuk mengumpul hanya maklumat yang diperlukan bagi mengendalikan papan, mencegah penyalahgunaan, menyokong pembayaran dan memahami penggunaan secara agregat.
Information we may process in production|Maklumat yang mungkin diproses dalam operasi sebenar
A random visitor identifier cookie for checkout continuity, click limits, and abuse prevention.|Kuki pengecam pelawat rawak untuk kesinambungan pembayaran, had klik dan pencegahan penyalahgunaan.
The submitted URL, category, payment amount, public listing metadata, and payment confirmation identifiers.|URL yang dihantar, kategori, jumlah bayaran, metadata penyenaraian awam dan pengecam pengesahan pembayaran.
Listing clicks, timestamp, a visitor identifier, and a hashed IP address for rate limiting and fraud reduction.|Klik penyenaraian, cap masa, pengecam pelawat dan alamat IP yang dicincang untuk mengehadkan kadar serta mengurangkan penipuan.
Basic technical data such as browser, referrer, IP address, and messages sent to support.|Data teknikal asas seperti pelayar, perujuk, alamat IP dan mesej yang dihantar kepada sokongan.
Payment data|Data pembayaran
RANKOFF does not store full card numbers, and never receives them. Dodo Payments handles the hosted checkout and returns the confirmation, amount, and order identifiers together with the details you entered there: your email address, name, phone number, billing address, invoice link, and your card's brand and last four digits. We keep those so we can reach you about your listing — including when someone outranks it — resend a receipt, and answer a dispute. Dodo's own terms and privacy notice apply to payment processing.|RANKOFF tidak menyimpan atau menerima nombor kad penuh. Dodo Payments mengendalikan halaman pembayaran dan mengembalikan pengesahan, jumlah serta pengecam pesanan bersama butiran yang anda masukkan: alamat e-mel, nama, nombor telefon, alamat pengebilan, pautan invois, jenama kad dan empat digit terakhir kad anda. Kami menyimpannya untuk menghubungi anda tentang penyenaraian — termasuk apabila dipintas — menghantar semula resit dan menjawab pertikaian. Terma dan notis privasi Dodo sendiri terpakai kepada pemprosesan pembayaran.
Campaign measurement|Pengukuran kempen
Campaign measurement uses a random identifier in this browser tab for up to 30 minutes, campaign labels from tagged links, review-form activity, tracked outbound clicks, and associated payment records. We store a salted hash of the identifier. Campaign labels must not contain personal information. Browser events do not confirm payment; only the payment provider can confirm settlement. Blocking storage or changing tabs or devices can prevent attribution.|Pengukuran kempen menggunakan pengecam rawak dalam tab pelayar ini sehingga 30 minit, label kempen daripada pautan bertanda, aktiviti borang semakan, klik keluar yang direkodkan dan rekod pembayaran berkaitan. Kami menyimpan cincangan pengecam yang ditambah nilai rawak. Label kempen tidak boleh mengandungi maklumat peribadi. Peristiwa pelayar tidak mengesahkan pembayaran; hanya penyedia pembayaran boleh mengesahkan penyelesaian. Menyekat storan atau menukar tab atau peranti boleh menghalang atribusi.
Public data and retention|Data awam dan penyimpanan
Rank, spend, listing name, image, description, category, and destination link are public and may be indexed. Payment and accounting records may be kept as required for tax, fraud, disputes, and legal obligations. Visitor identifiers and click-protection records are retained only as long as useful for those purposes.|Kedudukan, perbelanjaan, nama penyenaraian, imej, penerangan, kategori dan pautan destinasi adalah awam dan mungkin diindeks. Rekod pembayaran dan perakaunan boleh disimpan mengikut keperluan cukai, penipuan, pertikaian dan kewajipan undang-undang. Pengecam pelawat dan rekod perlindungan klik disimpan hanya selama berguna untuk tujuan tersebut.
Checkout model|Model pembayaran
RANKOFF uses a provider-hosted Dodo Payments checkout. RANKOFF creates a pending payment, sends the amount and payment identifier to Dodo, and publishes the rank only after confirmed settlement.|RANKOFF menggunakan halaman pembayaran yang dihoskan oleh Dodo Payments. RANKOFF mencipta pembayaran tertunda, menghantar jumlah serta pengecam pembayaran kepada Dodo dan menerbitkan kedudukan hanya selepas penyelesaian disahkan.
Every charge is a one-time payment for advertising placement services, made in the board's displayed currency. Charges are not deposits, wagers, stakes, contest entries, or stored value, and no charge participates in any prize distribution.|Setiap caj ialah bayaran sekali untuk perkhidmatan penempatan iklan, dalam mata wang yang dipaparkan pada papan. Caj bukan deposit, pertaruhan, penyertaan pertandingan atau nilai tersimpan, dan tiada caj terlibat dalam pengagihan hadiah.
Review|Semakan
Hosted checkout|Halaman pembayaran
Payment confirmed|Pembayaran disahkan
Rank published|Kedudukan diterbitkan
Supported payment experience|Pengalaman pembayaran yang disokong
The provider-hosted page shows available payment methods for the buyer's country and device, collects applicable taxes, and handles card security. RANKOFF never asks users to paste card numbers into the board.|Halaman yang dihoskan penyedia menunjukkan kaedah pembayaran yang tersedia untuk negara dan peranti pembeli, mengutip cukai yang berkenaan dan mengendalikan keselamatan kad. RANKOFF tidak pernah meminta pengguna menampal nombor kad pada papan.
`.trim().split('\n').map(line => {const i=line.indexOf('|');return [line.slice(0,i),line.slice(i+1)];})));
