/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/social-publisher/wrangler.jsonc --include-runtime=false workers/social-publisher/worker-configuration.d.ts` (hash: e82ff6dbe512db16b74bae4956af06a7)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	SOCIAL_PUBLISHING_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SOCIAL_PUBLISHING_ENABLED">> {}
}
declare module "*.js" {
	const value: string;
	export default value;
}
declare module "*.js" {
	const value: string;
	export default value;
}
declare module "*.js" {
	const value: string;
	export default value;
}
declare module "*.js" {
	const value: string;
	export default value;
}