/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/social-publisher/wrangler.jsonc --include-runtime=false workers/social-publisher/worker-configuration.d.ts` (hash: 5159cdebcda6ac84877e74448bac5a0c)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	SOCIAL_PUBLISHING_ENABLED: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SOCIAL_PUBLISHING_ENABLED">> {}
}
